# Generated by Django 5.2.5 on 2025-11-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_alter_bill_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='meter',
            name='instalacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meter',
            name='macrozona',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='meter',
            name='coverage',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
