# Generated by Django 5.2.5 on 2025-11-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_meter_direccion_meter_instalacion_meter_macrozona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='tarifa',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
