# Generated by Django 5.2.5 on 2025-11-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_bill_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
